In [26]:

from faker import Faker
import random
import pandas as pd
from bson import ObjectId
import datetime
import json

# Librerías de Pyhton para encriptar el password de los usuarios
import hashlib

## Declaración de variables globales y funciones auxiliares

### Cargar tags profesionales

In [27]:
# load data from json file
def load_data(file):
    import json
    with open(file) as f:
        data = json.load(f)
    return data

In [3]:
# Load courses from courses.json file
courses = load_data("File/courses.json")

ids_courses = []
for course in courses:
    ids_courses.append(course["_id"]["$oid"])

len(ids_courses)

19

In [5]:
# Load data from tags.json file
tags = load_data("File/tags.json")
tags

# Guardar solo los que profesional sea True
tags_profesional = []
tags_interests = []
for tag in tags:
    if tag["profesional"] == True:
        tags_profesional.append(tag)
    else:
        tags_interests.append(tag)

# Total de tags profesionales
print(len(tags_profesional))
# Total de tags intereses
print(len(tags_interests))

101
30

In [6]:
ids_interests = []
for tag in tags_interests:
    ids_interests.append(tag["_id"]["$oid"])

print(ids_interests)

ids_profesional = []
for tag in tags_profesional:
    ids_profesional.append(tag["_id"]["$oid"])

print(ids_profesional)

['64879ed95340903bb1ebb0fa', '64879ed95340903bb1ebb0fb', '64879ed95340903bb1ebb0fc', '64879ed95340903bb1ebb0fd', '64879ed95340903bb1ebb0fe', '64879ed95340903bb1ebb0ff', '64879ed95340903bb1ebb100', '64879ed95340903bb1ebb101', '64879ed95340903bb1ebb102', '64879ed95340903bb1ebb103', '64879ed95340903bb1ebb104', '64879ed95340903bb1ebb105', '64879ed95340903bb1ebb106', '64879ed95340903bb1ebb107', '64879ed95340903bb1ebb108', '64879ed95340903bb1ebb109', '64879ed95340903bb1ebb10a', '64879ed95340903bb1ebb10b', '64879ed95340903bb1ebb10c', '64879ed95340903bb1ebb10d', '64879ed95340903bb1ebb10e', '64879ed95340903bb1ebb10f', '64879ed95340903bb1ebb110', '64879ed95340903bb1ebb111', '64879ed95340903bb1ebb112', '64879ed95340903bb1ebb113', '64879ed95340903bb1ebb114', '64879ed95340903bb1ebb115', '64879ed95340903bb1ebb116', '64879ed95340903bb1ebb117']
['64879e9a5340903bb1ebb095', '64879e9a5340903bb1ebb096', '64879e9a5340903bb1ebb097', '64879e9a5340903bb1ebb098', '64879e9a5340903bb1ebb099', '64879e9a5340903bb1ebb09a', '64879e9a5340903bb1ebb09b', '64879e9a5340903bb1ebb09c', '64879e9a5340903bb1ebb09d', '64879e9a5340903bb1ebb09e', '64879e9a5340903bb1ebb09f', '64879e9a5340903bb1ebb0a0', '64879e9a5340903bb1ebb0a1', '64879e9a5340903bb1ebb0a2', '64879e9a5340903bb1ebb0a3', '64879e9a5340903bb1ebb0a4', '64879e9a5340903bb1ebb0a5', '64879e9a5340903bb1ebb0a6', '64879e9a5340903bb1ebb0a7', '64879e9a5340903bb1ebb0a8', '64879e9a5340903bb1ebb0a9', '64879e9a5340903bb1ebb0aa', '64879e9a5340903bb1ebb0ab', '64879e9a5340903bb1ebb0ac', '64879e9a5340903bb1ebb0ad', '64879e9a5340903bb1ebb0ae', '64879e9a5340903bb1ebb0af', '64879e9a5340903bb1ebb0b0', '64879e9a5340903bb1ebb0b1', '64879e9a5340903bb1ebb0b2', '64879e9a5340903bb1ebb0b3', '64879e9a5340903bb1ebb0b4', '64879e9a5340903bb1ebb0b5', '64879e9a5340903bb1ebb0b6', '64879e9a5340903bb1ebb0b7', '64879e9a5340903bb1ebb0b8', '64879e9a5340903bb1ebb0b9', '64879e9a5340903bb1ebb0ba', '64879e9a5340903bb1ebb0bb', '64879e9a5340903bb1ebb0bc', '64879e9a5340903bb1ebb0bd', '64879e9a5340903bb1ebb0be', '64879e9a5340903bb1ebb0bf', '64879e9a5340903bb1ebb0c0', '64879e9a5340903bb1ebb0c1', '64879e9a5340903bb1ebb0c2', '64879e9a5340903bb1ebb0c3', '64879e9a5340903bb1ebb0c4', '64879e9a5340903bb1ebb0c5', '64879e9a5340903bb1ebb0c6', '64879e9a5340903bb1ebb0c7', '64879e9a5340903bb1ebb0c8', '64879e9a5340903bb1ebb0c9', '64879e9a5340903bb1ebb0ca', '64879e9a5340903bb1ebb0cb', '64879e9a5340903bb1ebb0cc', '64879e9a5340903bb1ebb0cd', '64879e9a5340903bb1ebb0ce', '64879e9a5340903bb1ebb0cf', '64879e9a5340903bb1ebb0d0', '64879e9a5340903bb1ebb0d1', '64879e9a5340903bb1ebb0d2', '64879e9a5340903bb1ebb0d3', '64879e9a5340903bb1ebb0d4', '64879e9a5340903bb1ebb0d5', '64879e9a5340903bb1ebb0d6', '64879e9a5340903bb1ebb0d7', '64879e9a5340903bb1ebb0d8', '64879e9a5340903bb1ebb0d9', '64879e9a5340903bb1ebb0da', '64879e9a5340903bb1ebb0db', '64879e9a5340903bb1ebb0dc', '64879e9a5340903bb1ebb0dd', '64879e9a5340903bb1ebb0de', '64879e9a5340903bb1ebb0df', '64879e9a5340903bb1ebb0e0', '64879e9a5340903bb1ebb0e1', '64879e9a5340903bb1ebb0e2', '64879e9a5340903bb1ebb0e3', '64879e9a5340903bb1ebb0e4', '64879e9a5340903bb1ebb0e5', '64879e9a5340903bb1ebb0e6', '64879e9a5340903bb1ebb0e7', '64879e9a5340903bb1ebb0e8', '64879e9a5340903bb1ebb0e9', '64879e9a5340903bb1ebb0ea', '64879e9a5340903bb1ebb0eb', '64879e9a5340903bb1ebb0ec', '64879e9a5340903bb1ebb0ed', '64879e9a5340903bb1ebb0ee', '64879e9a5340903bb1ebb0ef', '64879e9a5340903bb1ebb0f0', '64879e9a5340903bb1ebb0f1', '64879e9a5340903bb1ebb0f2', '64879e9a5340903bb1ebb0f3', '64879e9a5340903bb1ebb0f4', '64879e9a5340903bb1ebb0f5', '64879e9a5340903bb1ebb0f6', '64879e9a5340903bb1ebb0f7', '64879e9a5340903bb1ebb0f8', '64879e9a5340903bb1ebb0f9']

In [7]:
# Lista con datos de los estudiantes de grado
studentsLevels = [
    {
        "name": "Grado IGE, Ingeniería y Gestión Empresarial",
        "tags_profesional": ids_profesional[82:],
        "courses": [
            {
                "name": "1º Grado IGE, Ingeniería y Gestión Empresarial",
                "id_course": ids_courses[0],
                "male": 42,
                "female": 23
            },
            {
                "name": "2º Grado IGE, Ingeniería y Gestión Empresarial",
                "id_course": ids_courses[1],
                "male": 33,
                "female": 9
            },
            {
                "name": "3º Grado IGE, Ingeniería y Gestión Empresarial",
                "id_course": ids_courses[2],
                "male": 18,
                "female": 10},
            {
                "name": "4º Grado IGE, Ingeniería y Gestión Empresarial",
                "id_course": ids_courses[3],
                "male": 21,
                "female": 8
            }

        ]
    },
    {
        "name": "Grado ADE, Creación y Dirección de Empresas",
        "tags_profesional": ids_profesional[82:],
        "courses": [
            {
                "name": "1º Grado ADE, Creación y Dirección de Empresas",
                "id_course": ids_courses[4],
                "male": 76,
                "female": 52
            },
            {
                "name": "2º Grado ADE, Creación y Dirección de Empresas",
                "id_course": ids_courses[5],
                "male": 53,
                "female": 39
            },
            {
                "name": "3º Grado ADE, Creación y Dirección de Empresas",
                "id_course": ids_courses[6],
                "male": 52,
                "female": 31
            },
            {
                "name": "4º Grado ADE, Creación y Dirección de Empresas",
                "id_course": ids_courses[7],
                "male": 50,
                "female": 22
            },
        ]
    }
]

# Lista con datos de los estudiantes de máster
studentsMaster = [
    {
        "name": "Máster Marketing y Venta Digital",
        "tags_profesional": ids_profesional[42:82],
        "groups": [
            {
                "name": "MMVD - A - Máster Marketing y Venta Digital",
                "id_course": ids_courses[8],
                "male": 20,
                "female": 10
            },
            {
                "name": "MMVD - B - Máster Marketing y Venta Digital",
                "id_course": ids_courses[9],
                "male": 15,
                "female": 16
            }
        ]
    },
    {
        "name": "Máster Fintech & Business Intelligence",
        "tags_profesional": ids_profesional[42:82],
        "groups": [
            {
                "name": "MFBI - Máster Fintech & Business Intelligence",
                "id_course": ids_courses[10],
                "male": 13,
                "female": 6
            }
        ]
    },
    {
        "name": "MBA Junior",
        "tags_profesional": ids_profesional[42:82],
        "groups": [
            {
                "name": "MBA Junior",
                "id_course": ids_courses[11],
                "male": 29,
                "female": 12
            }
        ]
    },

    {
        "name": "Máster Data Analytics",
        "tags_profesional": ids_profesional[42:82],
        "groups": [
            {
                "name": "MDA - Máster Data Analytics",
                "id_course": ids_courses[12],
                "male": 23,
                "female": 7
            }
        ]}
]

# Lista con datos de los estudiantes de bootcamp
studentBootcamps = [
    {
        "name": "Bootcamp Data Science",
        "tags_profesional": ids_profesional[:42],
        "groups": [
            {
                "name": "Bootcamp Data Science Full Time",
                "id_course": ids_courses[13],
                "male": 9,
                "female": 3
            },
            {
                "name": "Bootcamp Data Science Part Time",
                "id_course": ids_courses[14],
                "male": 5,
                "female": 0
            }
        ]
    },
    {
        "name": "Bootcamp Full Stack",
        "tags_profesional": ids_profesional[:42],
        "groups": [
            {
                "name": "Bootcamp Full Stack Full Time",
                "id_course": ids_courses[15],
                "male": 9,
                "female": 1
            },
            {
                "name": "Bootcamp Full Stack Part Time",
                "id_course": ids_courses[16],
                "male": 4,
                "female": 0
            }

        ]
    },
    {
        "name": "Bootcamp UX/UI",
        "tags_profesional": ids_profesional[:42],
        "groups": [
            {
                "name": "Bootcamp UX/UI",
                "id_course": ids_courses[17],
                "male": 5,
                "female": 2
            }
        ]
    },
    {
        "name": "Bootcamp Ciberseguridad",
        "tags_profesional": ids_profesional[:42],
        "groups": [
            {
                "name": "Bootcamp Ciberseguridad",
                "id_course": ids_courses[18],
                "male": 4,
                "female": 2
            }
        ]
    }
]

# Lista con los idiomas
languages = [
    {
        "name": "Castellano",
        "locale": "es_ES",
        "country": "España"
    },
    {
        "name": "Inglés",
        "locale": "en_US",
        "country": "Estados Unidos"
    },
    {
        "name": "Francés",
        "locale": "fr_FR",
        "country": "Francia"
    },
    {
        "name": "Alemán",
        "locale": "de_DE",
        "country": "Alemania"
    },
    {
        "name": "Italiano",
        "locale": "it_IT",
        "country": "Italia"
    },
    # {
    #     "name": "Ruso",
    #     "locale": "ru_RU"
    # },

    # {
    #     "name": "Árabe",
    #     "locale": "ar_SA"
    # },
    # {
    #     "name": "Chino",
    #     "locale": "zh_CN"
    # }
]
    
languagesNames = [language["name"] for language in languages]

# Listado situación laboral
situations = [ 
    "estudiante", "desempleado", "trabajando", "autonomo", "emprendedor"]

In [42]:

def encriptar_password(password):
    '''
    Función que encripta una contraseña utilizando el algoritmo SHA-256
    Argumentos:
        - password: contraseña a encriptar
    Devuelve:
        - password_encriptado: contraseña encriptada
    '''
    # Convertir la contraseña a bytes
    password_bytes = password.encode('utf-8')

    # Crear un objeto hash utilizando el algoritmo SHA-256
    hash_object = hashlib.sha256()

    # Actualizar el objeto hash con la contraseña en bytes
    hash_object.update(password_bytes)

    # Obtener la representación hexadecimal del hash
    password_encriptado = hash_object.hexdigest()

    # Devolver el password encriptado
    return password_encriptado

# Encriptar una contraseña
contrasena = input("Ingresa tu contraseña: ")
contrasena_encriptada = encriptar_password(contrasena)
print("La contraseña encriptada es:", contrasena_encriptada)

La contraseña encriptada es: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

In [8]:
# Función para generar habilidades
def generate_skills(course):
    random_skills_got = []
    random_skills_need = []
    random_numberL = random.choice([1, 2, 3, 4])
    if "Bootcamp Data Science" in course:
        # Generar random los ids de los skills de la lista ids_profesional de 0 al 41
        random_skills_got = random.sample(
            ids_profesional[0:12], k=min(random_numberL, 11))
        
        # variable para guardar los skills que no tiene random_skills_got
        random_skills = [skill for skill in ids_profesional[0:12] if skill not in random_skills_got]
        random_skills_need = random.sample(
            random_skills, k=min(random_numberL, len(random_skills)))
    elif "Bootcamp Full Stack" in course:
        random_skills_got = random.sample(
            ids_profesional[12:22], k=min(random_numberL, 10))
        random_skills = [skill for skill in ids_profesional[12:22] if skill not in random_skills_got]
        random_skills_need = random.sample(
            random_skills, k=min(random_numberL, len(random_skills)))
    elif course == "Bootcamp UX/UI":
        random_skills_got = random.sample(
            ids_profesional[22:32], k=min(random_numberL, 10))
        random_skills = [skill for skill in ids_profesional[22:32] if skill not in random_skills_got]
        random_skills_need = random.sample(
            random_skills, k=min(random_numberL, len(random_skills)))
    elif course == "Bootcamp Ciberseguridad":
        random_skills_got = random.sample(
            ids_profesional[32:42], k=min(random_numberL, 10))
        random_skills = [skill for skill in ids_profesional[32:42] if skill not in random_skills_got]
        random_skills_need = random.sample(
            random_skills, k=min(random_numberL, len(random_skills)))
    elif "Máster Marketing y Venta Digital" in course:
        random_skills_got = random.sample(
            ids_profesional[42:52], k=min(random_numberL, 10))
        random_skills = [skill for skill in ids_profesional[42:52] if skill not in random_skills_got]
        random_skills_need = random.sample(
            random_skills, k=min(random_numberL, len(random_skills)))
    elif "Máster Fintech & Business Intelligence" in course:
        random_skills_got = random.sample(
            ids_profesional[52:62], k=min(random_numberL, 10))
        random_skills = [skill for skill in ids_profesional[52:62] if skill not in random_skills_got]
        random_skills_need = random.sample(
            random_skills, k=min(random_numberL, len(random_skills)))
    elif "MBA Junior" in course:
        random_skills_got = random.sample(
            ids_profesional[62:72], k=min(random_numberL, 10))
        random_skills = [skill for skill in ids_profesional[62:72] if skill not in random_skills_got]
        random_skills_need = random.sample(
            random_skills, k=min(random_numberL, len(random_skills)))
    elif "Máster Data Analytics" in course:
        random_skills_got = random.sample(
            ids_profesional[72:82], k=min(random_numberL, 10))
        random_skills = [skill for skill in ids_profesional[72:82] if skill not in random_skills_got]
        random_skills_need = random.sample(
            random_skills, k=min(random_numberL, len(random_skills)))
    elif "Grado IGE, Ingeniería y Gestión Empresarial" in course:
        random_skills_got = random.sample(
            ids_profesional[82:92], k=min(random_numberL, 10))
        random_skills = [skill for skill in ids_profesional[82:92] if skill not in random_skills_got]
        random_skills_need = random.sample(
            random_skills, k=min(random_numberL, len(random_skills)))
    elif "Grado ADE, Creación y Dirección de Empresas" in course:
        random_skills_got = random.sample(
            ids_profesional[92:102], k=min(random_numberL, 10))
        random_skills = [skill for skill in ids_profesional[92:102] if skill not in random_skills_got]
        random_skills_need = random.sample(
            random_skills, k=min(random_numberL, len(random_skills)))
    return random_skills_got, random_skills_need

In [9]:
def generateStudents(gender, language, course, id_course):
    '''
    Función que genera un estudiante aleatorio con los datos proporcionados:
    Argumentos:
        gender: género del estudiante
        language: idioma del estudiante
        course: curso del estudiante
    Devuelve:
        student: diccionario con los datos del estudiante
    '''
    faker = Faker(language["locale"])
    random_skills=[]
    random_skills_got=[]
    random_skills_need=[]
    if gender == "male":
        name = faker.name_male()
    else:
        name = faker.name_female()

    names = name.lower().split()
    email = f"{names[0]}.{names[1]}@edem.es"
    birth_date = faker.date_of_birth(minimum_age=18, maximum_age=40)
    # Genera intereses
    random_numberI = random.choice([1, 2, 3, 4, 5])
    random_interests = random.sample(
        ids_interests, k=min(random_numberI, len(ids_interests)))
    # Genera Lenguajes
    random_numberL = random.choice([1, 2, 3, 4])
    remaining_languages = [
        lang for lang in languagesNames if lang != language["name"]]
    random_languages = random.sample(
        remaining_languages, k=min(random_numberL, len(remaining_languages)))
    selected_languages = [language["name"]] + random_languages
    # Generar país de acuerdo al idioma escogido
    country = language["country"]

    
    # Genera conocimientos
    #random_conocimientos = random.sample(
     #   ids_profesional, k=min(random_numberI, len(ids_profesional)))
    
    random_conocimientos, quieroAprender = generate_skills(course)

    # Generar random situacion laboral de acuerdo al curso escogido: si es de un curso de grado, será estudiante, si es de otro curso, será cualquiera
    if "Grado" in course:
        situationLaboral = "Estudiante"
    else:
        situationLaboral = random.choice([situations])


    

    # generate id from mongodb
    new_id = ObjectId()

    # Convertir el ObjectId a una cadena
    str_id = str(new_id)
    return {
        # "_id": str_id,
        "name": name,
        "email": email,
        "password": "728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d7191d042a6e8dd241e136",
        #"type": "student",
        "languages": selected_languages,
        "birth_date": birth_date,
        "country": country,
        "name_course": course,
        "course": id_course,
        "situationLaboral": situationLaboral,
        "role": "user",
        "dateCreated": datetime.datetime.utcnow().isoformat(),
        "gender": gender,
        "eventsConfi": [],
        "imageUrl":faker.image_url(),
        "firstOnBoard": True,
        "conocimientos": random_conocimientos,
        "quieroAprender": quieroAprender,
        "interests": random_interests
        
        
    }

## Generación de datos aleatorios para los estudiantes

In [10]:
# Genera estudiantes de grado
students = []
for career in studentsLevels:
    for course in career["courses"]:
        for i in range(1, (course["male"]+1)):
            language = random.choice(languages)
            students.append(generateStudents("male", language, course["name"], course["id_course"]))
        for i in range(1, (course["female"]+1)):
            language = random.choice(languages)
            students.append(generateStudents(
                "female", language, course["name"], course["id_course"]))

In [11]:
# Genera estudiantes de bootcamp
for bootcamp in studentBootcamps:
    for group in bootcamp["groups"]:
        for i in range(1, (group["male"]+1)):
            language = random.choice(languages)
            students.append(generateStudents("male", language,
                            f"{group['name']}", group["id_course"]))
        for i in range(1, (group["female"]+1)):
            language = random.choice(languages)
            students.append(generateStudents("female", language,
                            f"{group['name']}", group["id_course"]))

In [12]:
# Genera estudiantes de máster
for master in studentsMaster:
    for group in master["groups"]:
        for i in range(1, (group["male"]+1)):
            language = random.choice(languages)
            students.append(generateStudents("male", language,
                            f"{group['name']}", group["id_course"]))
        for i in range(1, (group["female"]+1)):
            language = random.choice(languages)
            students.append(generateStudents("female", language,
                            f"{group['name']}", group["id_course"]))

In [13]:
# Genera dataframe de estudiantes
df_students = pd.DataFrame(students)
df_students.head()

,name,email,password,languages,birth_date,country,name_course,course,situationLaboral,role,dateCreated,gender,eventsConfi,imageUrl,firstOnBoard,conocimientos,quieroAprender,interests
0,Dott. Calcedonio Canetta,dott..calcedonio@edem.es,728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d719...,"[Italiano, Alemán]",2005-04-15,Italia,"1º Grado IGE, Ingeniería y Gestión Empresarial",64879f03e785526bbd480f36,Estudiante,user,2023-06-12T22:51:44.323155,male,[],https://dummyimage.com/369x450,True,"[64879e9a5340903bb1ebb0e9, 64879e9a5340903bb1e...","[64879e9a5340903bb1ebb0e8, 64879e9a5340903bb1e...","[64879ed95340903bb1ebb10d, 64879ed95340903bb1e..."
1,Trinidad Pavón-Posada,trinidad.pavón-posada@edem.es,728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d719...,"[Castellano, Inglés, Alemán]",1990-02-21,España,"1º Grado IGE, Ingeniería y Gestión Empresarial",64879f03e785526bbd480f36,Estudiante,user,2023-06-12T22:51:44.340644,male,[],https://picsum.photos/672/241,True,[64879e9a5340903bb1ebb0e9],[64879e9a5340903bb1ebb0e8],"[64879ed95340903bb1ebb10c, 64879ed95340903bb1e..."
2,Univ.Prof. Torsten Eigenwillig MBA.,univ.prof..torsten@edem.es,728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d719...,"[Alemán, Inglés, Italiano, Francés]",1995-02-13,Alemania,"1º Grado IGE, Ingeniería y Gestión Empresarial",64879f03e785526bbd480f36,Estudiante,user,2023-06-12T22:51:44.356358,male,[],https://placekitten.com/808/80,True,"[64879e9a5340903bb1ebb0ee, 64879e9a5340903bb1e...","[64879e9a5340903bb1ebb0e8, 64879e9a5340903bb1e...","[64879ed95340903bb1ebb10b, 64879ed95340903bb1e..."
3,Nicolai Warmer,nicolai.warmer@edem.es,728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d719...,"[Alemán, Italiano, Castellano, Francés, Inglés]",2003-06-08,Alemania,"1º Grado IGE, Ingeniería y Gestión Empresarial",64879f03e785526bbd480f36,Estudiante,user,2023-06-12T22:51:44.368136,male,[],https://picsum.photos/415/977,True,"[64879e9a5340903bb1ebb0eb, 64879e9a5340903bb1e...","[64879e9a5340903bb1ebb0ec, 64879e9a5340903bb1e...","[64879ed95340903bb1ebb0fa, 64879ed95340903bb1e..."
4,Guiomar Baldomero Figueroa Castejón,guiomar.baldomero@edem.es,728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d719...,"[Castellano, Alemán, Italiano]",1995-07-26,España,"1º Grado IGE, Ingeniería y Gestión Empresarial",64879f03e785526bbd480f36,Estudiante,user,2023-06-12T22:51:44.379568,male,[],https://dummyimage.com/403x607,True,[64879e9a5340903bb1ebb0ed],[64879e9a5340903bb1ebb0ec],"[64879ed95340903bb1ebb10a, 64879ed95340903bb1e..."

## Validación de los datos generados

In [62]:
# Obtener un dataframe con las columnas course y id_course sin repetirse
df_courses = df_students[["name_course", "course"]].drop_duplicates()
df_courses

                                        name_course                    course
0    1º Grado IGE, Ingeniería y Gestión Empresarial  64879f03e785526bbd480f36
65   2º Grado IGE, Ingeniería y Gestión Empresarial  64879f03e785526bbd480f37
107  3º Grado IGE, Ingeniería y Gestión Empresarial  64879f03e785526bbd480f38
135  4º Grado IGE, Ingeniería y Gestión Empresarial  64879f03e785526bbd480f39
164  1º Grado ADE, Creación y Dirección de Empresas  64879f03e785526bbd480f3a
292  2º Grado ADE, Creación y Dirección de Empresas  64879f03e785526bbd480f3b
384  3º Grado ADE, Creación y Dirección de Empresas  64879f04e785526bbd480f3c
467  4º Grado ADE, Creación y Dirección de Empresas  64879f04e785526bbd480f3d
539                 Bootcamp Data Science Full Time  64879f0de785526bbd480f43
551                 Bootcamp Data Science Part Time  64879f0de785526bbd480f44
556                   Bootcamp Full Stack Full Time  64879f0de785526bbd480f45
566                   Bootcamp Full Stack Part Time  64879f0de785526bbd480f46
570                                  Bootcamp UX/UI  64879f0ee785526bbd480f47
577                         Bootcamp Ciberseguridad  64879f0ee785526bbd480f48
583     MMVD - A - Máster Marketing y Venta Digital  64879f0ae785526bbd480f3e
613     MMVD - B - Máster Marketing y Venta Digital  64879f0ae785526bbd480f3f
644   MFBI - Máster Fintech & Business Intelligence  64879f0ae785526bbd480f40
663                                      MBA Junior  64879f0ae785526bbd480f41
704                     MDA - Máster Data Analytics  64879f0ae785526bbd480f42

In [14]:
len(df_courses)

19

In [29]:
# Mostrar la columna password 
df_students["password"].unique()

array(['728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d7191d042a6e8dd241e136'],
      dtype=object)

In [74]:
time=datetime.datetime
print(time)

<class 'datetime.datetime'>

## Información de los estudiantes y cursos

In [15]:
# Mostrar estudiates de master
master = df_students[df_students["name_course"].str.contains("Máster")]
# Mostrar los valores unicos de course
master["name_course"].unique()

array(['MMVD - A - Máster Marketing y Venta Digital',
       'MMVD - B - Máster Marketing y Venta Digital',
       'MFBI - Máster Fintech & Business Intelligence',
       'MDA - Máster Data Analytics'], dtype=object)

In [16]:
# Mostrar estudiantes de grado
grade = df_students[df_students["name_course"].str.contains("Grado")]
# Mostrar los valores unicos de course
grade["name_course"].unique()

array(['1º Grado IGE, Ingeniería y Gestión Empresarial',
       '2º Grado IGE, Ingeniería y Gestión Empresarial',
       '3º Grado IGE, Ingeniería y Gestión Empresarial',
       '4º Grado IGE, Ingeniería y Gestión Empresarial',
       '1º Grado ADE, Creación y Dirección de Empresas',
       '2º Grado ADE, Creación y Dirección de Empresas',
       '3º Grado ADE, Creación y Dirección de Empresas',
       '4º Grado ADE, Creación y Dirección de Empresas'], dtype=object)

In [17]:
# Mostrar estudiantes de bootcamp
bootcamp = df_students[df_students["name_course"].str.contains("Bootcamp")]
# Mostrar los valores unicos de course
bootcamp["name_course"].unique()

array(['Bootcamp Data Science Full Time',
       'Bootcamp Data Science Part Time', 'Bootcamp Full Stack Full Time',
       'Bootcamp Full Stack Part Time', 'Bootcamp UX/UI',
       'Bootcamp Ciberseguridad'], dtype=object)

In [18]:
# Cantidad de estudiantes por curso
df_students["name_course"].value_counts()

name_course
1º Grado ADE, Creación y Dirección de Empresas    128
2º Grado ADE, Creación y Dirección de Empresas     92
3º Grado ADE, Creación y Dirección de Empresas     83
4º Grado ADE, Creación y Dirección de Empresas     72
1º Grado IGE, Ingeniería y Gestión Empresarial     65
2º Grado IGE, Ingeniería y Gestión Empresarial     42
MBA Junior                                         41
MMVD - B - Máster Marketing y Venta Digital        31
MMVD - A - Máster Marketing y Venta Digital        30
MDA - Máster Data Analytics                        30
4º Grado IGE, Ingeniería y Gestión Empresarial     29
3º Grado IGE, Ingeniería y Gestión Empresarial     28
MFBI - Máster Fintech & Business Intelligence      19
Bootcamp Data Science Full Time                    12
Bootcamp Full Stack Full Time                      10
Bootcamp UX/UI                                      7
Bootcamp Ciberseguridad                             6
Bootcamp Data Science Part Time                     5
Bootcamp Full Stack Part Time                       4
Name: count, dtype: int64

In [19]:
# Total de estudiantes
df_students["name_course"].value_counts().sum()

734

In [20]:
# Información dataset
df_students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 734 entries, 0 to 733
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              734 non-null    object
 1   email             734 non-null    object
 2   password          734 non-null    object
 3   languages         734 non-null    object
 4   birth_date        734 non-null    object
 5   country           734 non-null    object
 6   name_course       734 non-null    object
 7   course            734 non-null    object
 8   situationLaboral  734 non-null    object
 9   role              734 non-null    object
 10  dateCreated       734 non-null    object
 11  gender            734 non-null    object
 12  eventsConfi       734 non-null    object
 13  imageUrl          734 non-null    object
 14  firstOnBoard      734 non-null    bool
 15  conocimientos     734 non-null    object
 16  quieroAprender    734 non-null    object
 17  interests         734 non-null    object
dtypes: bool(1), object(17)
memory usage: 98.3+ KB

### Validaciones

In [14]:
# Mostrar si hay nombres duplicados en el dataset de estudiantes 
df_students[df_students.duplicated(['name'], keep=False)]

Empty DataFrame
Columns: [name, email, password, languages, birth_date, country, name_course, course, situationLaboral, role, dateCreated, gender, eventsConfi, imageUrl, firstOnBoard, conocimientos, quieroAprender, interests]
Index: []

In [15]:
# Mostrar si hay correos duplicados en el dataset de estudiantes
df_students[df_students.duplicated(['email'], keep=False)]

,name,email,password,languages,birth_date,country,name_course,course,situationLaboral,role,dateCreated,gender,eventsConfi,imageUrl,firstOnBoard,conocimientos,quieroAprender,interests
135,Robert de la Toussaint,robert.de@edem.es,728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d719...,"[Francés, Castellano, Italiano, Alemán]",2004-12-17,Francia,"4º Grado IGE, Ingeniería y Gestión Empresarial",64879f03e785526bbd480f39,Estudiante,user,2023-06-12T22:51:45.911527,male,[],https://picsum.photos/677/538,True,"[64879e9a5340903bb1ebb0ea, 64879e9a5340903bb1e...","[64879e9a5340903bb1ebb0ef, 64879e9a5340903bb1e...","[64879ed95340903bb1ebb111, 64879ed95340903bb1e..."
690,Robert de Labbé,robert.de@edem.es,728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d719...,"[Francés, Castellano, Inglés, Alemán, Italiano]",2001-09-06,Francia,MBA Junior,64879f0ae785526bbd480f41,"[estudiante, desempleado, trabajando, autonomo...",user,2023-06-12T22:51:54.594802,male,[],https://picsum.photos/18/234,True,"[64879e9a5340903bb1ebb0d4, 64879e9a5340903bb1e...","[64879e9a5340903bb1ebb0d9, 64879e9a5340903bb1e...","[64879ed95340903bb1ebb117, 64879ed95340903bb1e..."

In [16]:
# Cambiar el email a estudiante Miguel Ángel Leocadio Arnal Ruano
df_students.loc[df_students["name"] == "Robert de la Toussaint", "email"] = " robert.toussaint@edem.es"

# Mostrar email de Miguel Ángel Leocadio Arnal Ruano
df_students.loc[df_students["name"] == "Robert de la Toussaint", "email"]

135     robert.toussaint@edem.es
Name: email, dtype: object

In [17]:
# Cambiar el email a estudiante Miguel Ángel Leocadio Arnal Ruano
df_students.loc[df_students["name"] == "Robert de Labbé", "email"] = " robert.labbé@edem.es"

# Mostrar email de Miguel Ángel Leocadio Arnal Ruano
df_students.loc[df_students["name"] == "Robert de Labbé", "email"]

690     robert.labbé@edem.es
Name: email, dtype: object

In [18]:
# Verificar si hay correos duplicados en el dataset de estudiantes
df_students[df_students.duplicated(['email'], keep=False)]

Empty DataFrame
Columns: [name, email, password, languages, birth_date, country, name_course, course, situationLaboral, role, dateCreated, gender, eventsConfi, imageUrl, firstOnBoard, conocimientos, quieroAprender, interests]
Index: []

In [19]:
# Eliminar la columna name_course del dataframe de estudiantes
df_students_final = df_students.drop(columns=["name_course"])
df_students_final.head()

,name,email,password,languages,birth_date,country,course,situationLaboral,role,dateCreated,gender,eventsConfi,imageUrl,firstOnBoard,conocimientos,quieroAprender,interests
0,Dott. Calcedonio Canetta,dott..calcedonio@edem.es,728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d719...,"[Italiano, Alemán]",2005-04-15,Italia,64879f03e785526bbd480f36,Estudiante,user,2023-06-12T22:51:44.323155,male,[],https://dummyimage.com/369x450,True,"[64879e9a5340903bb1ebb0e9, 64879e9a5340903bb1e...","[64879e9a5340903bb1ebb0e8, 64879e9a5340903bb1e...","[64879ed95340903bb1ebb10d, 64879ed95340903bb1e..."
1,Trinidad Pavón-Posada,trinidad.pavón-posada@edem.es,728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d719...,"[Castellano, Inglés, Alemán]",1990-02-21,España,64879f03e785526bbd480f36,Estudiante,user,2023-06-12T22:51:44.340644,male,[],https://picsum.photos/672/241,True,[64879e9a5340903bb1ebb0e9],[64879e9a5340903bb1ebb0e8],"[64879ed95340903bb1ebb10c, 64879ed95340903bb1e..."
2,Univ.Prof. Torsten Eigenwillig MBA.,univ.prof..torsten@edem.es,728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d719...,"[Alemán, Inglés, Italiano, Francés]",1995-02-13,Alemania,64879f03e785526bbd480f36,Estudiante,user,2023-06-12T22:51:44.356358,male,[],https://placekitten.com/808/80,True,"[64879e9a5340903bb1ebb0ee, 64879e9a5340903bb1e...","[64879e9a5340903bb1ebb0e8, 64879e9a5340903bb1e...","[64879ed95340903bb1ebb10b, 64879ed95340903bb1e..."
3,Nicolai Warmer,nicolai.warmer@edem.es,728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d719...,"[Alemán, Italiano, Castellano, Francés, Inglés]",2003-06-08,Alemania,64879f03e785526bbd480f36,Estudiante,user,2023-06-12T22:51:44.368136,male,[],https://picsum.photos/415/977,True,"[64879e9a5340903bb1ebb0eb, 64879e9a5340903bb1e...","[64879e9a5340903bb1ebb0ec, 64879e9a5340903bb1e...","[64879ed95340903bb1ebb0fa, 64879ed95340903bb1e..."
4,Guiomar Baldomero Figueroa Castejón,guiomar.baldomero@edem.es,728e6cca58a5b904a5a9c6bac40bfeae8733909ee7d719...,"[Castellano, Alemán, Italiano]",1995-07-26,España,64879f03e785526bbd480f36,Estudiante,user,2023-06-12T22:51:44.379568,male,[],https://dummyimage.com/403x607,True,[64879e9a5340903bb1ebb0ed],[64879e9a5340903bb1ebb0ec],"[64879ed95340903bb1ebb10a, 64879ed95340903bb1e..."

In [20]:
# Shape del dataframe de estudiantes
df_students_final.shape

(734, 17)

In [21]:
# Información del dataframe de estudiantes
df_students_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 734 entries, 0 to 733
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              734 non-null    object
 1   email             734 non-null    object
 2   password          734 non-null    object
 3   languages         734 non-null    object
 4   birth_date        734 non-null    object
 5   country           734 non-null    object
 6   course            734 non-null    object
 7   situationLaboral  734 non-null    object
 8   role              734 non-null    object
 9   dateCreated       734 non-null    object
 10  gender            734 non-null    object
 11  eventsConfi       734 non-null    object
 12  imageUrl          734 non-null    object
 13  firstOnBoard      734 non-null    bool
 14  conocimientos     734 non-null    object
 15  quieroAprender    734 non-null    object
 16  interests         734 non-null    object
dtypes: bool(1), object(16)
memory usage: 92.6+ KB

In [22]:
# Guardar dataset en json
df_students_final.to_json("File/students.json", orient="records", force_ascii=False)       # orient="records" para que guarde cada registro como un objeto json

In [23]:
# Guardar dataset en csv
df_students_final.to_csv("File/students.csv", index=False, encoding="utf-8")